[package]
name = "morse_rsdk"
version = "0.1.0"
edition = "2021"

[dependencies]
rp2040-hal = { version = "0.11.0", features = ["binary-info", "critical-section-impl", "rt", "defmt"] }
panic-halt = "0.2.0"
defmt = "0.3"
rp-pico = "0.9.0"
cortex-m = "0.7.2"
cortex-m-rt = "0.7"
critical-section = {version = "1.2.0"}
embedded-hal = "1.0.0"
rp2040-boot2 = "0.3.0"
heapless = { version = "0.7.16", default-features = false }
nb = "1.1.0"
# Replace the pac dependency with the correct one
rp2040-pac = "0.6.0"
embedded-time = "0.12.1"

[[bin]]
name = "adc"
path = "src/bin/adc.rs"

[[bin]]
name = "gpio"
path = "src/bin/gpio.rs"

[[bin]]
name = "interrupt"
path = "src/bin/interrupt.rs"

[[bin]]
name = "pwm"
path = "src/bin/pwm.rs"

[[bin]]
name = "uart"
path = "src/bin/uart.rs"

[[bin]]
name = "transmitter"
path = "src/bin/transmitter.rs"

[[bin]]
name = "receiver"
path = "src/bin/receiver.rs"

[[bin]]
name = "benchmarks"
path = "src/bin/benchmarks.rs"

[features]
default = []
test = []

[profile.release]
debug = true
opt-level = "z"
lto = true